# Generated by Django 4.2.17 on 2025-03-21 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_playlist_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("image", "Image"),
                    ("video", "Video"),
                    ("view", "External View"),
                ],
                default="image",
                editable=False,
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="content",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="content",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="content",
            name="view_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="content",
            name="mediafile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.mediafile",
            ),
        ),
        migrations.AddConstraint(
            model_name="subgroup",
            constraint=models.UniqueConstraint(
                fields=("name", "group"), name="unique_name_group"
            ),
        ),
    ]
