# Generated by Django 4.2.17 on 2025-03-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_content_content_type_content_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("image", "Image"),
                    ("video", "Video"),
                    ("view", "External View"),
                ],
                editable=False,
                max_length=10,
            ),
        ),
    ]
