# Generated by Django 4.2.17 on 2025-03-23 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_content_content_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("view_name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="content",
            name="view_name",
        ),
        migrations.AddField(
            model_name="content",
            name="custom_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.custompage",
            ),
        ),
    ]
