# Generated by Django 4.2.17 on 2025-03-30 02:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_custompage_remove_content_view_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Display",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "guid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("active", models.BooleanField(default=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
