# Generated by Django 4.2.17 on 2025-03-30 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_display"),
    ]

    operations = [
        migrations.AddField(
            model_name="display",
            name="Playlist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.playlist",
            ),
        ),
        migrations.AddField(
            model_name="display",
            name="group",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.group"
            ),
        ),
        migrations.AddField(
            model_name="display",
            name="subgroup",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.subgroup",
            ),
        ),
    ]
